/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/auth/apple": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Sign in with Apple
         * @description Verifies the identity token against Apple's JWKS and returns an opaque session token. full_name only arrives from Apple on first authorization. 201 when the account is new, 200 otherwise.
         */
        post: {
            parameters: {
                query?: never;
                header?: {
                    "X-Device-Id"?: string;
                };
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        identity_token: string;
                        authorization_code: string;
                        /** @description Raw nonce; its SHA256 must equal the token's nonce claim */
                        nonce: string;
                        full_name?: {
                            givenName?: string | null;
                            familyName?: string | null;
                        } | null;
                    };
                };
            };
            responses: {
                /** @description existing account signed in */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: {
                                token: string;
                                user: components["schemas"]["User"];
                                is_new: boolean;
                            };
                        };
                    };
                };
                /** @description new account created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: {
                                token: string;
                                user: components["schemas"]["User"];
                                is_new: boolean;
                            };
                        };
                    };
                };
                /** @description token could not be verified */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description account suspended */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/google": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Sign in with Google
         * @description Verifies the id token against Google's JWKS (iss accounts.google.com, aud the iOS client id, email_verified).
         */
        post: {
            parameters: {
                query?: never;
                header?: {
                    "X-Device-Id"?: string;
                };
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        id_token: string;
                    };
                };
            };
            responses: {
                /** @description existing account signed in */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: {
                                token: string;
                                user: components["schemas"]["User"];
                                is_new: boolean;
                            };
                        };
                    };
                };
                /** @description new account created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: {
                                token: string;
                                user: components["schemas"]["User"];
                                is_new: boolean;
                            };
                        };
                    };
                };
                /** @description token could not be verified */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Sign out this session
         * @description Deletes only the calling session row and unlinks its device.
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description signed out */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description not signed in */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/clubs/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Club detail
         * @description The Club shape. Anonymous by default; a hidden club is 404 unless the viewer can manage it (R-5, R-6, R-9).
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    slug: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description AC-1: an active club with three upcoming meets */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: components["schemas"]["Club"];
                        };
                    };
                };
                /** @description AC-2: a hidden club */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/clubs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Club directory
         * @description Active clubs, nearest first with distance_m when near is present, most followed first otherwise. q matches the name by trigram, within 80 km when near is present (R-7, R-18).
         */
        get: {
            parameters: {
                query?: {
                    /** @description lat,lng */
                    near?: string;
                    radius_km?: number;
                    q?: string;
                    limit?: number;
                    cursor?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description AC-3: clubs at 2 and 10 km, ordered, with distance_m */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: components["schemas"]["ClubSummary"][];
                            meta: {
                                next_cursor: string | null;
                                total: number | null;
                            };
                        };
                    };
                };
            };
        };
        put?: never;
        /**
         * Create a club
         * @description Post-launch (clubs R-10). Returns 403 not_enabled while clubs_self_service is off.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description clubs_self_service is off */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/clubs/{slug}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Meets a club hosts
         * @description EventSummary rows, upcoming first, or the most recent past meets with past=true.
         */
        get: {
            parameters: {
                query?: {
                    past?: boolean;
                    limit?: number;
                    cursor?: string;
                };
                header?: never;
                path: {
                    slug: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description upcoming meets */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: components["schemas"]["EventSummary"][];
                            meta: {
                                next_cursor: string | null;
                                total: number | null;
                            };
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/clubs/{slug}/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Club members
         * @description Active memberships only, oldest first, each with the member's role, cursor paginated. Blocked members are omitted for a signed-in viewer (R-8).
         */
        get: {
            parameters: {
                query?: {
                    limit?: number;
                    cursor?: string;
                };
                header?: never;
                path: {
                    slug: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description active members with roles */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: (components["schemas"]["MiniProfile"] & {
                                /** @enum {string} */
                                role: "owner" | "admin" | "member";
                            })[];
                            meta: {
                                next_cursor: string | null;
                                total: number | null;
                            };
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/clubs/{id}/membership": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Join a club
         * @description Post-launch (R-10). Returns 403 not_enabled while clubs_self_service is off.
         */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description AC-7: clubs_self_service is off */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        post?: never;
        /**
         * Leave a club
         * @description Post-launch (clubs R-10). Returns 403 not_enabled while clubs_self_service is off.
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description clubs_self_service is off */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/clubs/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update a club
         * @description Post-launch (clubs R-10). Returns 403 not_enabled while clubs_self_service is off.
         */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description clubs_self_service is off */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/v1/clubs/{id}/invites": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Invite a member
         * @description Post-launch (clubs R-10). Returns 403 not_enabled while clubs_self_service is off.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description clubs_self_service is off */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/clubs/{id}/invite_code": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Rotate the invite code
         * @description Post-launch (clubs R-10). Returns 403 not_enabled while clubs_self_service is off.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description clubs_self_service is off */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/clubs/{id}/members/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Remove a member
         * @description Post-launch (clubs R-10). Returns 403 not_enabled while clubs_self_service is off.
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                    user_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description clubs_self_service is off */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        /**
         * Change a member's role
         * @description Post-launch (clubs R-10). Returns 403 not_enabled while clubs_self_service is off.
         */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                    user_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description clubs_self_service is off */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/v1/devices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Register or update a device
         * @description Upserts on anonymous_id so push registration and the home area survive until sign-in.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** Format: uuid */
                        anonymous_id: string;
                        /** @enum {string} */
                        platform: "ios" | "android" | "web";
                        push_token?: string | null;
                        app_version?: string;
                        home_location?: {
                            lat: number;
                            lng: number;
                        } | null;
                        timezone?: string;
                    };
                };
            };
            responses: {
                /** @description device updated */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: components["schemas"]["Device"];
                        };
                    };
                };
                /** @description device registered */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: components["schemas"]["Device"];
                        };
                    };
                };
                /** @description invalid platform */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/devices/{anonymous_id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                anonymous_id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update push token, home location, or timezone */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    anonymous_id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        push_token?: string | null;
                        push_enabled?: boolean;
                        app_version?: string;
                        home_location?: {
                            lat: number;
                            lng: number;
                        } | null;
                        timezone?: string;
                    };
                };
            };
            responses: {
                /** @description device updated */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: components["schemas"]["Device"];
                        };
                    };
                };
                /** @description unknown device */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/v1/events/{id}/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Confirm the schedule is current
         * @description The host (the user host, an owner or admin of the hosting club, or a platform admin) answers "Still happening?": last_confirmed_at moves to now, dormant_at clears, and a dormant event is re-materialized (R-24, R-28). Anyone else gets 403.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description AC-18: an admin confirms a dormant event */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: components["schemas"]["Event"];
                        };
                    };
                };
                /** @description anonymous */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description AC-18: a member with no role may not confirm */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description unknown event */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/events/map": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Map pins in a viewport
         * @description One MapPin per event (its earliest scheduled occurrence in the window) inside bbox, the soonest 500 by starts_at, with meta.truncated when the box held more. bbox is required and at most 5 degrees wide.
         */
        get: {
            parameters: {
                query: {
                    /** @description w,s,e,n */
                    bbox: string;
                    from?: string;
                    to?: string;
                    "tags[]"?: ("jdm" | "euro" | "exotic" | "classic" | "muscle" | "truck" | "ev" | "bike" | "all")[];
                    recurring?: boolean;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description AC-5: 501 occurrences give the soonest 500 pins and truncated */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: components["schemas"]["MapPin"][];
                            meta: {
                                truncated: boolean;
                            };
                        };
                    };
                };
                /** @description bbox missing or wider than 5 degrees */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/events/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Event detail
         * @description The Event shape. Anonymous by default. A draft is 404 unless the viewer can edit; an unlisted event needs its share token; a cancelled or hidden event is 410 gone with up to three nearby meets when near is sent; a dormant event is 200 with dormant true. A recurring event whose materialized horizon is under 60 days re-materializes on read (R-14).
         */
        get: {
            parameters: {
                query?: {
                    /** @description Share token for an unlisted event */
                    token?: string;
                    /** @description lat,lng; fills nearby on a 410 */
                    near?: string;
                };
                header?: never;
                path: {
                    slug: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description AC-1: published recurring event with sponsorships and six dates */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: components["schemas"]["Event"];
                        };
                    };
                };
                /** @description AC-22: a draft is not readable by the public */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description AC-3: a cancelled event is gone, with nearby meets when near is sent */
                410: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List events
         * @description EventSummary rows from indexed PostGIS queries. near or bbox selects the earliest scheduled occurrence per event in the window (default now to +14 days, at most 90); host, sponsor, or q without geo lists events directly, announced ones included with a null next_occurrence. With near, radius_km defaults to 32 (80 with q) and clamps at 160. bbox with near returns the box with distance_m from near.
         */
        get: {
            parameters: {
                query?: {
                    /** @description lat,lng */
                    near?: string;
                    radius_km?: number;
                    /** @description w,s,e,n */
                    bbox?: string;
                    from?: string;
                    to?: string;
                    /** @description Any tag matches */
                    "tags[]"?: ("jdm" | "euro" | "exotic" | "classic" | "muscle" | "truck" | "ev" | "bike" | "all")[];
                    /** @description true keeps cadence other than once */
                    recurring?: boolean;
                    /** @description Trigram match on title and host name, ILIKE on venue name */
                    q?: string;
                    /** @description user:<id>, club:<id>, or sponsor:<id> */
                    host?: string;
                    /** @description Events the sponsor hosts or is attached to */
                    sponsor?: string;
                    /** @description distance needs near */
                    sort?: "date" | "distance";
                    /** @description Host, sponsor, and search lists only: the most recent past meets instead of upcoming ones. Ignored with near or bbox. */
                    past?: boolean;
                    limit?: number;
                    cursor?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description AC-1: nearby meets from Lido, nearest first within a day */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: components["schemas"]["EventSummary"][];
                            meta: {
                                next_cursor: string | null;
                                total: number | null;
                            };
                        };
                    };
                };
                /** @description near with an unusable window, sort, or coordinates */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Service health
         * @description Liveness check: database reachability and Solid Queue lag. 503 while the database is unreachable.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description service is healthy */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @enum {string} */
                            status: "ok" | "degraded";
                            db: boolean;
                            queue_lag_s: number | null;
                        };
                    };
                };
                /** @description database unreachable */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @enum {string} */
                            status: "ok" | "degraded";
                            db: boolean;
                            queue_lag_s: number | null;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Current user
         * @description The signed-in user with profile, linked identities, and notification preferences.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description current user */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: components["schemas"]["User"];
                        };
                    };
                };
                /** @description not signed in */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        /**
         * Delete account
         * @description Soft-deletes now (sessions revoked, devices unlinked) and purges after 30 days; signing in again before then restores the account.
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description deletion scheduled */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: {
                                /** Format: date-time */
                                purge_after: string;
                            };
                        };
                    };
                };
            };
        };
        options?: never;
        head?: never;
        /**
         * Update account fields
         * @description Phase 0 accepts profile.handle and profile.display_name only.
         */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        profile: {
                            handle?: string;
                            display_name?: string;
                        };
                    };
                };
            };
            responses: {
                /** @description updated */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: components["schemas"]["User"];
                        };
                    };
                };
                /** @description handle taken or invalid */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/v1/events/{id}/occurrences": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Upcoming occurrences of an event
         * @description Upcoming scheduled and cancelled dates, oldest first, cursor paginated (R-22).
         */
        get: {
            parameters: {
                query?: {
                    limit?: number;
                    cursor?: string;
                };
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description AC-23: three scheduled and one cancelled upcoming date */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: components["schemas"]["Occurrence"][];
                            meta: {
                                next_cursor: string | null;
                                total: number | null;
                            };
                        };
                    };
                };
                /** @description a crafted or malformed cursor */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description an event the viewer cannot see */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/occurrences/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * One occurrence
         * @description The Occurrence shape with its event summary, timezone, and override note.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description AC-23: a cancelled occurrence carries its timezone and note */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: components["schemas"]["Occurrence"];
                        };
                    };
                };
                /** @description unknown occurrence */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/sponsors/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Sponsor detail
         * @description The Sponsor shape with up to three upcoming meets, each labelled host or sponsor (R-6, R-8). A hidden sponsor is 404.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    slug: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description AC-1: a venue sponsor hosting one meet and attached to two */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: components["schemas"]["Sponsor"];
                        };
                    };
                };
                /** @description AC-3: a hidden sponsor */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/sponsors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Sponsor directory
         * @description Active sponsors, nearest first with distance_m when near is present, most followed first otherwise; kind and q filter (R-7, R-17).
         */
        get: {
            parameters: {
                query?: {
                    /** @description lat,lng */
                    near?: string;
                    radius_km?: number;
                    kind?: "brand" | "vendor" | "venue";
                    q?: string;
                    limit?: number;
                    cursor?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description AC-4: sponsors at 3 and 12 km, ordered, with distance_m */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: components["schemas"]["SponsorSummary"][];
                            meta: {
                                next_cursor: string | null;
                                total: number | null;
                            };
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/sponsors/{slug}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Meets a sponsor hosts or backs
         * @description EventSummary rows with relation host or sponsor, deduplicated with host winning (R-8). Equivalent to GET /events?sponsor=<id>.
         */
        get: {
            parameters: {
                query?: {
                    past?: boolean;
                    limit?: number;
                    cursor?: string;
                };
                header?: never;
                path: {
                    slug: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description hosted and attached meets */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: (components["schemas"]["EventSummary"] & {
                                /** @enum {string} */
                                relation: "host" | "sponsor";
                            })[];
                            meta: {
                                next_cursor: string | null;
                                total: number | null;
                            };
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/sponsors/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update a sponsor
         * @description Post-launch (R-11). Returns 403 not_enabled while sponsors_self_service is off.
         */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description AC-10: sponsors_self_service is off */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/v1/users/{handle}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Public profile
         * @description The Profile shape (R-7, R-8). Anonymous by default; a suspended or deleted account is 404.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    handle: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description AC-1: a host with a club membership and three published meets */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: components["schemas"]["Profile"];
                        };
                    };
                };
                /** @description AC-2: a suspended account */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/users/{handle}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Meets a user hosts
         * @description Published events with host_type User, upcoming first.
         */
        get: {
            parameters: {
                query?: {
                    past?: boolean;
                    limit?: number;
                    cursor?: string;
                };
                header?: never;
                path: {
                    handle: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description hosted meets */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: components["schemas"]["EventSummary"][];
                            meta: {
                                next_cursor: string | null;
                                total: number | null;
                            };
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/users/{handle}/clubs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Clubs a user belongs to
         * @description ClubSummary rows for active memberships, each with the member's role. Hidden clubs are omitted.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    handle: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description active memberships */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: components["schemas"]["ClubSummary"][];
                            meta: {
                                next_cursor: string | null;
                                total: number | null;
                            };
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Error: {
            error: {
                code: string;
                message: string;
                details?: {
                    [key: string]: unknown;
                } | null;
            };
        };
        Profile: {
            /** Format: uuid */
            id: string;
            handle: string;
            display_name: string;
            bio?: string | null;
            avatar_url?: string | null;
            home_label?: string | null;
            is_host: boolean;
            links: {
                [key: string]: string;
            };
            /** @description Active memberships, each with the member's role */
            clubs: components["schemas"]["ClubSummary"][];
            counts: {
                [key: string]: number;
            };
            viewer: {
                following: boolean;
                blocked: boolean;
                is_self: boolean;
                reported: boolean;
            };
        };
        User: {
            /** Format: uuid */
            id: string;
            email?: string | null;
            /** @enum {string} */
            role: "member" | "moderator" | "admin";
            /** @enum {string} */
            status: "active" | "suspended" | "deleted";
            /** Format: date-time */
            created_at: string;
            profile: components["schemas"]["Profile"];
            identities: {
                /** @enum {string} */
                provider: "apple" | "google";
                email: string | null;
            }[];
            notification_prefs: {
                [key: string]: unknown;
            };
            unread_notifications_count?: number;
        };
        /** @description One shape for every host type (ADR 0010); switch on type only for the link target. */
        Host: {
            /** @enum {string} */
            type: "user" | "club" | "sponsor";
            /** Format: uuid */
            id: string;
            slug: string | null;
            name: string | null;
            avatar_url: string | null;
            verified: boolean;
            /** @enum {string|null} */
            kind: "brand" | "vendor" | "venue" | null;
        };
        EventSummary: {
            /** Format: uuid */
            id: string;
            slug: string;
            title: string;
            cover_url: string | null;
            cover_blurhash: string | null;
            tags: ("jdm" | "euro" | "exotic" | "classic" | "muscle" | "truck" | "ev" | "bike" | "all")[];
            recurring: boolean;
            rrule_text: string | null;
            /** @description Null only while the host row is missing; HostConsistencyJob reports the drift */
            host: components["schemas"]["Host"] | null;
            venue: {
                /** Format: uuid */
                id: string;
                name: string;
                city: string | null;
                location: {
                    lat: number;
                    lng: number;
                };
            };
            next_occurrence: {
                /** Format: uuid */
                id: string;
                /** Format: date-time */
                starts_at: string;
                /** Format: date-time */
                ends_at: string;
                timezone: string;
                going_count: number;
                /** @enum {string} */
                status: "scheduled" | "cancelled" | "completed";
            } | null;
            /** @description Meters from near, computed in PostGIS; null without near */
            distance_m: number | null;
            source: {
                type: string | null;
                url: string;
            } | null;
            claimed: boolean;
            /** @enum {string} */
            cadence: "once" | "weekly" | "monthly" | "seasonal" | "announced";
            /** @description Unclaimed and not confirmed within 30 days (R-25) */
            stale: boolean;
            /** Format: date-time */
            last_confirmed_at: string | null;
            sponsors_preview: {
                /** Format: uuid */
                id: string;
                slug: string;
                name: string;
                logo_url: string | null;
                /** @enum {string} */
                role: "presented_by" | "coffee" | "vendor" | "partner";
            }[];
        };
        MiniProfile: {
            /** Format: uuid */
            id: string;
            handle: string;
            display_name: string;
            avatar_url: string | null;
        };
        ClubSummary: {
            /** Format: uuid */
            id: string;
            slug: string;
            name: string;
            avatar_url: string | null;
            verified: boolean;
            home_label: string | null;
            members_count: number;
            followers_count: number;
            /** @enum {string} */
            join_policy: "open" | "invite_only";
            /** @description Meters from near, computed in PostGIS; null without near */
            distance_m: number | null;
            /**
             * @description The viewed member's role, set only on GET /users/:handle/clubs
             * @enum {string|null}
             */
            role: "owner" | "admin" | "member" | null;
        };
        /** @description Club detail: ClubSummary plus the page's own fields. */
        Club: components["schemas"]["ClubSummary"] & {
            description: string | null;
            banner_url: string | null;
            links: {
                [key: string]: string;
            };
            events_count: number;
            upcoming_events: components["schemas"]["EventSummary"][];
            members_preview: components["schemas"]["MiniProfile"][];
            viewer: {
                following: boolean;
                membership: {
                    /** @enum {string} */
                    role: "owner" | "admin" | "member";
                    /** @enum {string} */
                    status: "active" | "invited" | "requested";
                } | null;
                can_manage: boolean;
            };
        };
        /** @description Sponsor detail: SponsorSummary plus the page's own fields. */
        Sponsor: components["schemas"]["SponsorSummary"] & {
            description: string | null;
            banner_url: string | null;
            website: string | null;
            links: {
                [key: string]: string;
            };
            events_count: number;
            upcoming_events: (components["schemas"]["EventSummary"] & {
                /** @enum {string} */
                relation: "host" | "sponsor";
            })[];
            viewer: {
                following: boolean;
            };
        };
        SponsorSummary: {
            /** Format: uuid */
            id: string;
            slug: string;
            name: string;
            /** @enum {string} */
            kind: "brand" | "vendor" | "venue";
            logo_url: string | null;
            verified: boolean;
            tagline: string | null;
            followers_count: number;
            home_label: string | null;
            /** @description Meters from near, computed in PostGIS; null without near */
            distance_m: number | null;
        };
        /** @description Event detail: EventSummary plus the fields only the detail screen needs. */
        Event: components["schemas"]["EventSummary"] & {
            description: string | null;
            parking_note: string | null;
            rrule: string | null;
            /** Format: date-time */
            dtstart: string | null;
            duration_minutes: number;
            /** @enum {string} */
            rsvp_mode: "open" | "count_only" | "off";
            capacity: number | null;
            /** @enum {string} */
            status: "draft" | "published" | "cancelled";
            /** @enum {string} */
            visibility: "public" | "unlisted";
            /** @description Out of lists and the map, page still served (R-27) */
            dormant: boolean;
            /** @description Only ever true for the host or an admin; the public gets 410 */
            hidden: boolean;
            external_host_name: string | null;
            venue: {
                /** Format: uuid */
                id: string;
                name: string;
                address_line1: string | null;
                address_line2: string | null;
                city: string | null;
                region: string | null;
                postal_code: string | null;
                country: string;
                timezone: string;
                location: {
                    lat: number;
                    lng: number;
                };
            };
            upcoming_occurrences: {
                /** Format: uuid */
                id: string;
                /** Format: date-time */
                starts_at: string;
                /** Format: date-time */
                ends_at: string;
                timezone: string;
                going_count: number;
                /** @enum {string} */
                status: "scheduled" | "cancelled" | "completed";
                override_note: string | null;
            }[];
            sponsorships: {
                sponsor: components["schemas"]["SponsorSummary"];
                /** @enum {string} */
                role: "presented_by" | "coffee" | "vendor" | "partner";
                note: string | null;
                position: number;
            }[];
            viewer: {
                following: boolean;
                /** @enum {string|null} */
                rsvp: "going" | null;
                can_edit: boolean;
                can_claim: boolean;
                /** @enum {string|null} */
                claim_status: "pending" | null;
                reported: boolean;
            };
            photos_count: number;
            comments_count: number;
            followers_count: number;
        };
        Occurrence: {
            /** Format: uuid */
            id: string;
            event: components["schemas"]["EventSummary"];
            /** Format: date-time */
            starts_at: string;
            /** Format: date-time */
            ends_at: string;
            timezone: string;
            /** @enum {string} */
            status: "scheduled" | "cancelled" | "completed";
            override_note: string | null;
            going_count: number;
            interested_count: number;
            check_in_count: number;
            going_preview: {
                [key: string]: unknown;
            }[];
            viewer: {
                /** @enum {string|null} */
                rsvp: "going" | null;
                checked_in: boolean;
            };
        };
        MapPin: {
            /**
             * Format: uuid
             * @description The occurrence
             */
            id: string;
            /** Format: uuid */
            event_id: string;
            slug: string;
            lat: number;
            lng: number;
            /** Format: date-time */
            starts_at: string;
            title: string;
            going_count: number;
        };
        Device: {
            /** Format: uuid */
            anonymous_id: string;
            /** @enum {string} */
            platform: "ios" | "android" | "web";
            push_enabled: boolean;
            push_token_present: boolean;
            app_version?: string | null;
            timezone?: string | null;
            /** Format: uuid */
            user_id?: string | null;
            home_location?: {
                lat: number;
                lng: number;
            } | null;
            /** Format: date-time */
            last_seen_at?: string | null;
        };
    };
    responses: never;
    parameters: {
        /** @description Client-generated device UUID sent on every request from mobile and web */
        deviceId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
