import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { describe, expect, expectTypeOf, it } from 'vitest';

import type {
  ApiErrorBody,
  DeviceResponse,
  HealthResponse,
  JsonRequest,
  JsonResponse,
  MeResponse,
  SignInResponse,
  User,
} from './index';

const generated = readFileSync(fileURLToPath(new URL('./generated.d.ts', import.meta.url)), 'utf8');

describe('@curb/types', () => {
  it('commits the openapi-typescript output with every Phase 0 path', () => {
    expect(generated).toContain('This file was auto-generated by openapi-typescript.');
    for (const path of [
      '/v1/auth/apple',
      '/v1/auth/google',
      '/v1/auth/session',
      '/v1/devices',
      '/v1/me',
      '/v1/health',
    ]) {
      expect(generated).toContain(`"${path}": {`);
    }
  });

  it('aliases resolve to the schema shapes (checked by tsc)', () => {
    expectTypeOf<User['role']>().toEqualTypeOf<'member' | 'moderator' | 'admin'>();
    expectTypeOf<User['profile']['handle']>().toEqualTypeOf<string>();
    expectTypeOf<ApiErrorBody['error']['code']>().toEqualTypeOf<string>();
    expectTypeOf<MeResponse['data']>().toEqualTypeOf<User>();
    expectTypeOf<SignInResponse['data']['token']>().toEqualTypeOf<string>();
    expectTypeOf<SignInResponse['data']['is_new']>().toEqualTypeOf<boolean>();
    expectTypeOf<DeviceResponse['data']['platform']>().toEqualTypeOf<'ios' | 'android' | 'web'>();
    expectTypeOf<HealthResponse['status']>().toEqualTypeOf<'ok' | 'degraded'>();
    expectTypeOf<JsonRequest<'/v1/auth/google', 'post'>['id_token']>().toEqualTypeOf<string>();
    expectTypeOf<JsonResponse<'/v1/health', 'get', 503>['db']>().toEqualTypeOf<boolean>();
  });
});
