import { ROLES, SCHEMES, type TokensSource } from './types';

const HEADER = 'Generated by build.ts from tokens.json. Do not edit.';

type FlatColors = Record<string, string>;

function flatColors(tokens: TokensSource, theme: string, scheme: string): FlatColors {
  const set = tokens.themes[theme][scheme as 'light' | 'dark'];
  const out: FlatColors = {};
  for (const role of ROLES) out[role] = set[role].$value;
  return out;
}

interface FontStacks {
  display: string[];
  ui: string[];
}

function fontStacks(tokens: TokensSource): FontStacks {
  const families = tokens.typography.families as Record<
    string,
    { $value: string; fallback?: string[] }
  >;
  const stack = (key: string) => [families[key].$value, ...(families[key].fallback ?? [])];
  return { display: stack('display'), ui: stack('ui') };
}

function cssStack(stack: string[]): string {
  return stack.map((f) => (/[ ]/.test(f) ? `"${f}"` : f)).join(',');
}

function numericEntries(section: Record<string, unknown>): Array<[string, number]> {
  return Object.entries(section).filter((e): e is [string, number] => typeof e[1] === 'number');
}

// dist/tokens.ts: themes, getTheme, typography, spacing, radius, glass,
// motion, and the types ThemeName, Scheme, Role, ThemeColors (R-2).
export function emitTokensTs(tokens: TokensSource): string {
  const themeNames = Object.keys(tokens.themes);
  const themes: Record<string, unknown> = {};
  for (const name of themeNames) {
    themes[name] = {
      name: tokens.themes[name].name,
      story: tokens.themes[name].story,
      light: flatColors(tokens, name, 'light'),
      dark: flatColors(tokens, name, 'dark'),
    };
  }
  const themeNameUnion = themeNames.map((n) => JSON.stringify(n)).join(' | ');
  return `// ${HEADER}

export const roles = ${JSON.stringify(ROLES)} as const;
export type Role = (typeof roles)[number];
export type Scheme = ${SCHEMES.map((s) => JSON.stringify(s)).join(' | ')};
export type ThemeName = ${themeNameUnion};
export type ThemeColors = Record<Role, string>;

export interface Theme {
  name: string;
  story: string;
  light: ThemeColors;
  dark: ThemeColors;
}

export const themes: Record<ThemeName, Theme> = ${JSON.stringify(themes, null, 2)};

export const defaultTheme: ThemeName = ${JSON.stringify(tokens.meta.defaultTheme)};
export const defaultScheme: Scheme = "light";

// Falls back to the default theme for an unknown name and to light for an
// unknown scheme (R-5).
export function getTheme(name: string = defaultTheme, scheme: string = defaultScheme): ThemeColors {
  const theme = Object.hasOwn(themes, name) ? themes[name as ThemeName] : themes[defaultTheme];
  return scheme === "dark" ? theme.dark : theme.light;
}

export const typography = ${JSON.stringify(tokens.typography, null, 2)} as const;

export const spacing = ${JSON.stringify(tokens.spacing, null, 2)} as const;

export const radius = ${JSON.stringify(tokens.radius, null, 2)} as const;

export const glass = ${JSON.stringify(tokens.glass, null, 2)} as const;

export const motion = ${JSON.stringify(tokens.motion, null, 2)} as const;
`;
}

function colorDecls(colors: FlatColors): string {
  return ROLES.map((role) => `--color-${role}:${colors[role]}`).join(';');
}

// dist/tokens.css: :root is the default theme light, prefers-color-scheme
// switches :root to its dark scheme, every variant is addressable as
// [data-theme][data-scheme], plus font, spacing, and radius variables (R-20).
export function emitTokensCss(tokens: TokensSource): string {
  const def = tokens.meta.defaultTheme;
  const fonts = fontStacks(tokens);
  const base = [
    colorDecls(flatColors(tokens, def, 'light')),
    `--font-display:${cssStack(fonts.display)}`,
    `--font-ui:${cssStack(fonts.ui)}`,
    ...numericEntries(tokens.spacing).map(([k, v]) => `--spacing-${k}:${v}px`),
    ...numericEntries(tokens.radius).map(([k, v]) => `--radius-${k}:${v}px`),
  ].join(';');

  const lines = [`/* ${HEADER} */`, `:root{${base}}`];
  lines.push(
    `@media (prefers-color-scheme: dark){:root{${colorDecls(flatColors(tokens, def, 'dark'))}}}`,
  );
  for (const theme of Object.keys(tokens.themes)) {
    for (const scheme of SCHEMES) {
      lines.push(
        `[data-theme="${theme}"][data-scheme="${scheme}"]{${colorDecls(
          flatColors(tokens, theme, scheme),
        )}}`,
      );
    }
  }
  return lines.join('\n') + '\n';
}

// dist/tailwind.theme.js: role names mapped to var(--color-<role>) for
// NativeWind and web Tailwind configs (package README).
export function emitTailwindTheme(tokens: TokensSource): string {
  const colors: Record<string, string> = {};
  for (const role of ROLES) colors[role] = `var(--color-${role})`;
  const fonts = fontStacks(tokens);
  const theme = {
    colors,
    fontFamily: { display: fonts.display, ui: fonts.ui },
    spacing: Object.fromEntries(numericEntries(tokens.spacing).map(([k, v]) => [k, `${v}px`])),
    borderRadius: Object.fromEntries(numericEntries(tokens.radius).map(([k, v]) => [k, `${v}px`])),
  };
  return `// ${HEADER}\nexport default ${JSON.stringify(theme, null, 2)};\n`;
}

// Declaration next to tailwind.theme.js so a TypeScript tailwind.config can
// import it under strict settings.
export function emitTailwindThemeDts(): string {
  return [
    `// ${HEADER}`,
    'declare const theme: {',
    '  colors: Record<string, string>;',
    '  fontFamily: { display: string[]; ui: string[] };',
    '  spacing: Record<string, string>;',
    '  borderRadius: Record<string, string>;',
    '};',
    'export default theme;',
    '',
  ].join('\n');
}
